[package]
name = "gdbstub"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
num-traits = { version = "0.2", default-features = false }

[features]
default = []
std = []
